---
resources:
- name: seven-stages-of-bosh
  type: git
  source:
    uri: https://github.com/engineerbetter/7-stages-of-bosh.git

- name: kf-pipelines
  type: git
  source:
    uri: git@github.com:EngineerBetter/kf-pipelines.git
    private_key: ((git_private_key))
    branch: prod


jobs:
- name: set-pipeline
  serial: true
  plan:
  - get: seven-stages-of-bosh
    trigger: true
  - set_pipeline: self
    file: seven-stages-of-bosh/ci/pipeline.yml

- name: deploy-dev
  serial: true
  plan:
  - get: seven-stages-of-bosh
    trigger: true
    passed: [set-pipeline]
  - get: kf-pipelines
  - &generate-kubeconfig
    task: generate-kubeconfig
    file: kf-pipelines/ci/tasks/generate-kubeconfig/task.yml
    params:
      GOOGLE_CREDENTIALS: ((ebkf-prod-app-developer-creds.gcp_credentials_json))
      REGION: ((ebkf-prod-app-developer-creds.region))
      CLUSTER: ((ebkf-prod-app-developer-creds.cluster_name))
  - task: kf-push
    file: kf-pipelines/ci/tasks/kf-cli/task.yml
    vars:
      kf_version: ((ebkf-prod-version))
    input_mapping:
      input: seven-stages-of-bosh
    params:
      ARGS: push --space development --manifest input/manifest.yml --path input

- name: deploy-staging
  serial: true
  plan:
  - get: seven-stages-of-bosh
    passed: [deploy-dev]
    trigger: true
  - get: kf-pipelines
  - *generate-kubeconfig
  - task: kf-push
    file: kf-pipelines/ci/tasks/kf-cli/task.yml
    vars:
      kf_version: ((ebkf-prod-version))
    input_mapping:
      input: seven-stages-of-bosh
    params:
      ARGS: push --space staging --manifest input/manifest.yml --path input

- name: deploy-prod
  serial: true
  plan:
  - get: seven-stages-of-bosh
    passed: [deploy-staging]
    trigger: false
  - get: kf-pipelines
  - *generate-kubeconfig
  - task: kf-push
    file: kf-pipelines/ci/tasks/kf-cli/task.yml
    vars:
      kf_version: ((ebkf-prod-version))
    input_mapping:
      input: seven-stages-of-bosh
    params:
      ARGS: push --space production --manifest input/manifest.yml --path input
